# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tenthusiast
email: your-email@domain.com
description: >
  Stumble upon a problem, think about it, solve it and share it !
logo: "assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gwillmann.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Grégoire Willmann'
bio: >
  French entrepreneur
author_image: "assets/images/author.jpg"
twitter_username: lejonqc
github_username:  gwillmann

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
